### ISSUE TITLE
example of inference in C++ (ONNX Runtime, TensorRT, OpenVINO)

### ISSUE THREAD

**Issue by Sem4ik228** [AakiraOtok/Project_VU#1]
Please write example of export this model in some inference framework. This is necessary because this project positions itself as a very fast action detector.

**Comment by AakiraOtok** [comment]
Hello, thank you for your interest in the project, and I apologize for the delayed response.

Currently, I am working with Pytorch and am not familiar with other frameworks. Therefore, at the moment, I can only support you in working with Pytorch. There are two options for the inference part that I currently have: using a camera for direct detection or loading data from the **ucf101-24** and **avav2.2** datasets to inference. If you are comfortable with Pytorch, I will quickly provide instructions for these two options.

**Comment by Sem4ik228** [comment]
I mean, this project positions itself like a real-time fast action detection neural network. It seems to be good idea that something like ONNX export included in  this project.

**Comment by AakiraOtok** [comment]
Thank you for your suggestion. After completing the instructions, I will update it to support ONNX.
