### ISSUE TITLE
On the issue of pre training weights.

### ISSUE THREAD

**Issue by xiegedaimazhenfeijin** [AakiraOtok/Project_VU#6]
Hello, I used your pre training weights to detect and encountered a suspected problem where the pre training weights are different from the tensor required by the network. May I ask what possible problems may have occurred? Is it due to my improper operation? Attached below is my error code. (Backbone3D uses an i3D model, with pretrain_path set as the weight path)
RuntimeError: Error(s) in loading state_dict for YOLO2Stream:
        size mismatch for detection_head.cls.0.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]).
        size mismatch for detection_head.cls.0.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for detection_head.cls.1.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]).
        size mismatch for detection_head.cls.1.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for detection_head.cls.2.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]).
        size mismatch for detection_head.cls.2.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]).

**Comment by xiegedaimazhenfeijin** [comment]
> Hello, I used your pre training weights to detect and encountered a suspected problem where the pre training weights are different from the tensor required by the network. May I ask what possible problems may have occurred? Is it due to my improper operation? Attached below is my error code. (Backbone3D uses an i3D model, with pretrain_path set as the weight path) RuntimeError: Error(s) in loading state_dict for YOLO2Stream: size mismatch for detection_head.cls.0.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]). size mismatch for detection_head.cls.0.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]). size mismatch for detection_head.cls.1.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]). size mismatch for detection_head.cls.1.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]). size mismatch for detection_head.cls.2.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 256, 1, 1]). size mismatch for detection_head.cls.2.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([24]).

**Comment by AakiraOtok** [comment]
Hello, thank you for asking the question.

It seems that you have mistakenly used the AVAv2.2 (80 classes) checkpoint for ucf101-24 (24 classes).
